external:
  uri:
    items: https://api.mercadolibre.com/items/{0}
    children: https://api.mercadolibre.com/items/{0}/children
  date:
    pattern: yyyy-MM-dd'T'HH:mm:ss.SSS
  health:
    slots: 5
    split: 60

## MySQL - Hibernate
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meli
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
